### ISSUE TITLE
localisation of controls (e.g. 'Grouped', 'Stacked')

### ISSUE THREAD

**Issue by fopsdev** [angularjs-nvd3-directives/angularjs-nvd3-directives#104]
and here goes another question :) thanks again for this brilliant piece of work!
how can i localise the control - texts in the following chart?
http://plnkr.co/edit/IYV66U?p=preview

**Comment by hotohoto** [comment]
You might be able to do that like below.

`chart.controlLabels({"grouped":"XXX","stacked":"YYY"})`
