### ISSUE TITLE
Cannot read property 1 of undefined.

### ISSUE THREAD

**Issue by novodinia** [angularjs-nvd3-directives/angularjs-nvd3-directives#112]
Receiving the error `Cannot read property 1 of undefined` with this code:
https://gist.github.com/novodinia/8464147
Issue #111 is very much related since I'm doing the same thing here:
- Using the example stacked chart from examples/
- And I'm deleting a few pieces of data to receive an error message.

**Comment by karna41317** [comment]
@cmaurer I read JSON from one of my analytics service, that will be dynamic data, and each series will not have data of same length. Is there any workaround for it ?

**Comment by Ragzzy-R** [comment]
this is a serious issue. I am making a chart dashboard for my company's internal timeseet management system. I will be showing a barchart of how many programmer-hours is totally spent on a day on multiple projects. somedays there will be one or two projects with no work done. here is how it looks like
![bar](https://cloud.githubusercontent.com/assets/2220953/26403164/dd46ab8e-40aa-11e7-8d26-541060b9f8ca.png)

so there is no way I can keep the length same. will there be a fix for this?  :disappointed:
