### ISSUE TITLE
pie.values() is no longer supported error in nv.d3.js 

### ISSUE THREAD

**Issue by ghost** [angularjs-nvd3-directives/angularjs-nvd3-directives#13]
I am trying to make simple pie chart, but the console returns this error : 

"pie.values() is no longer supported."

**Comment by hel123** [comment]
I am begineer for sugarcrm,i am not able to trace the error and followed all the steps which described above.can any one help me,still same error is coming in my console i.e,pie.values() is no longer supported used Asol reports
