### ISSUE TITLE
Click event does not work when useInteractiveGuideline is enabled

### ISSUE THREAD

**Issue by abij** [angularjs-nvd3-directives/angularjs-nvd3-directives#136]
In my line chart I enabled useInteractiveGuideline and the clickEvents are not propagated anymore.

addition to directive line 890:

```
 angular.module( 'nvd3ChartDirectives', [] )
    .directive( 'nvd3LineChart', [
        function () {
            return {
                restrict: 'EA',
                scope: {
                   ...
                   interactive: '@',
                    useinteractiveguideline: '@', <<---- this
```

controller:

```
$scope.$on('elementClick.directive', function(angularEvent, event){
    console.log('Why am I not triggered anymore?')
});
```

html:

```
<nvd3-line-chart
                    data="displayHist"
                    id="timeline"
                    height="350"
                    showLegend="true"
                    showControls="false"
                    showXAxis="true"
                    showYAxis="true"
                    tooltips="true"
                    interactive="true"
                    useInteractiveGuideline="true">
```

changing the useInteractiveGuideline to false will again tigger the event to the console.

versions
1.  angularjs-nvd3-directives  0.0.5
2.  nv.d3  1.1.15b
3.  d3  3.1.5

**Comment by olivierSemet** [comment]
Same issue. Any suggestion?

**Comment by relwell** [comment]
I've used jiggering to fix it, but that's still a hack. The error condition should have a more helpful message, but I understand that's a problem with nvd3.

**Comment by portante** [comment]
@olivierSemet, @relwell, have either of you tried this with the community version of nvd3?  See: https://github.com/nvd3-community/nvd3

**Comment by olivierSemet** [comment]
Nope, I will. Thanks

**Comment by relwell** [comment]
Looks like updating to nvd3 1.7.1 fixes this
