### ISSUE TITLE
Charts do not show up

### ISSUE THREAD

**Issue by BernhardRode** [angularjs-nvd3-directives/angularjs-nvd3-directives#173]
As discussed in #170 I'm going to open a new issue for the following problem.

We're using angularjs-nvd3-directives inside of some Tabs. When the Tab, containing the chart is being shown by ng-show, the chart does not get redrawn correctly. The only solution is resizing the browser window/frame.

http://plnkr.co/edit/23UvXij6SiI9Gk4ZCjYu?p=preview

Is it possible to force the chart to redraw itself?

**Comment by gabrielrasdale** [comment]
had the same issue, found using ng-if instead of ng-show resolved the issue

**Comment by gbrmachado** [comment]
I had the same issue here. My solution was something different. I used the following callback in my chart's options:
`callback: function(chart) {
                  chart.update();
                },`

Apparently it's working well.
