### ISSUE TITLE
Disable tooltips for one serie only

### ISSUE THREAD

**Issue by Maxwell2022** [angularjs-nvd3-directives/angularjs-nvd3-directives#195]
I'm using `line` + `bar` serie to display data:

``` html
<nvd3-line-plus-bar-chart
        data="exampleData"
        id="exampleId"
        width="390"
        height="180"
        xAxisTickValues="[0, 6, 12, 18, 23]"
        xAxisTickFormat="xAxisTickFormat()"
        y1AxisTickFormat="y1AxisTickFormat()"
        y2AxisTickFormat="y2AxisTickFormat()"
        interactive="true"
        tooltips="true"
        showLegend="false"
        tooltipcontent="toolTipContentFunction()"
    >
        <svg></svg>
    </nvd3-line-plus-bar-chart>
```

I want to disable the tooltip for the line char but keep the one from the bar chart but I can't manage to find how to do it. It appears that the tooltip for the bar chart are never showing up and I'm not sure if this is due to a `z-index` issue or something else.

I've tried to set the tooltips to false for the `line` serie, but I still have the tooltips showing up with `undefined` value in it:

``` js
{
    "color": "rgb(91,183,91)",
    "key":"Average waiting time",
    "bar": true,
     "values": [...]
},
{
    "tooltip": false,
    "color": "#E01B5D",
    "key" : "Courses",
    "values" : [...]
}
```

![screen shot 2014-05-20 at 4 38 36 pm](https://cloud.githubusercontent.com/assets/670701/3023593/7d1e752c-dfe9-11e3-9c1b-f1bf5d616b23.png)

When I mous over the `bar` serie, the `line` tooltip is showing up because it's close to the `bar`

**Comment by rajraja** [comment]
Hi Maxwell2022, but tooltips are showing either for bar or line chart, can you please help me to show for both line chart as well as a bar chart ?
