### ISSUE TITLE
Resizing in Resizable Div

### ISSUE THREAD

**Issue by tinyRabbit** [angularjs-nvd3-directives/angularjs-nvd3-directives#291]
I'm unable to get the directives to resize when the parent div resizes. Have tried setting svg to auto, height and width to auto, and changing them to 100% etc.  Has anyone been able to get these things to resize with a div?

**Comment by ss-bb** [comment]
Hi . Having same pb here.
Could you tell me where you change the svg viewBox in the lib plz? 
Thank
