### ISSUE TITLE
Error on resizing the chart

### ISSUE THREAD

**Issue by ateev** [angularjs-nvd3-directives/angularjs-nvd3-directives#336]
Hello. Thanks for such an awesome directive. 
I am experiencing one problem. Whenever I try to resize the browser window, it throws me an error on the console.

Error:   

`Uncaught TypeError: Cannot read property 'update' of null`  

This error comes on the line [141](https://github.com/krispo/angular-nvd3/blob/master/dist/angular-nvd3.js#L141)

I am using the v1.0.0-beta. Thanks for your time.

**Comment by praveenaj** [comment]
I'm getting the same issue. Any solution?

**Comment by ateev** [comment]
@praveenaj Not yet. Let me know if you find any.

**Comment by praveenaj** [comment]
Found a fix. I made a small change to line 143

```
scope.chart.resizeHandler = nv.utils.windowResize(function() { scope.chart && scope.chart.update(); });
```
