### ISSUE TITLE
Render End Event

### ISSUE THREAD

**Issue by GustavoCostaW** [angularjs-nvd3-directives/angularjs-nvd3-directives#343]
Hello, I need an event when the chart was successfully loaded I check http://cmaurer.github.io/angularjs-nvd3-directives/events.html but Render End not works for me, can you help me? thx!

**Comment by leocongote** [comment]
Hi gustavo, i have the same issue, do you have any new clue?

**Comment by GustavoCostaW** [comment]
I change to https://github.com/krispo/angular-nvd3 @leocongote
