### ISSUE TITLE
Autoresize graph in a div with changing width/height

### ISSUE THREAD

**Issue by ss-bb** [angularjs-nvd3-directives/angularjs-nvd3-directives#362]
HI. 
I add a line chart directive with no width/height in a div which can be extend. 

When i extend the div, nothing change on the graph, but when I Open/Close/Move the FF console view, the graph resize auto on the new Div max size. 

An issue tell about the viewBox which have to be manipulate. my svg viewbox is "0 0 undefined undefined".

**Comment by ss-bb** [comment]
Just in case sb had the pb, put  this somewhere : 
window.dispatchEvent(new Event('resize'));

**Comment by bsh314** [comment]
This is having issues on Firefox current stable.

Desc: Svg resizes well after height/width changes, but inner elements are keeping their size. This happens only after few re-sizings.
