### ISSUE TITLE
Passing JSON data url instead of data

### ISSUE THREAD

**Issue by rafialikhan** [angularjs-nvd3-directives/angularjs-nvd3-directives#45]
Is there any plans to add dataurl instead of data so that d3.json can be called to fetch json at render time.

**Comment by SandeepApsingekar** [comment]
Hi,

I would like to know how do you pass json data as url. Can you give me an example. Because instead of sending the data in the code, I want to send it as a json file. Is it possible. I really appreciate your help. 

Thanks!

Regards,
Sandeep
