### ISSUE TITLE
Multi-bar label type percent?

### ISSUE THREAD

**Issue by dagumak** [angularjs-nvd3-directives/angularjs-nvd3-directives#59]
I looked through the source and noticed it didn&#39;t have a label type. Is there a way to make percentage label type for multi bar charts and disable the decimal point?

Also, is there a way to actually show the value in the bar on a stacked bar chart?

Great work on this library! Thanks in advance!

**Comment by udaykanth3** [comment]
how to display values(x,y) on the line chart graph using NVD3.. directly on the line chart i need to display ?? if possible reply me ...

**Comment by tilluran006** [comment]
Its straight forward
add 
.showValues(true)
 in you code
