### ISSUE TITLE
Pie chart - show labels as name and percentage

### ISSUE THREAD

**Issue by fizerkhan** [angularjs-nvd3-directives/angularjs-nvd3-directives#92]
In Pie chart, I wanted to show the label as `name ( count - percentage)`. I could only see showLabels option true or false.

I need a function to configure the labels that i want to display in the pie chart. Is it possible?

**Comment by aneesh-nirguna** [comment]
.labelType(function (d) { return d.data.x+": "+d.data.y })

you can refer this

https://stackoverflow.com/questions/16233551/nvd3-editing-labels-in-pie-chart-legend
